### ISSUE TITLE
how to modify the ip address arachni listen to

### ISSUE THREAD

**Issue by tuhaolam** [sergekatzmann/openvas8-complete#1]
as your readme shows, the arachni listen to 'docker_host_ip:9292', but i test severval times, it listen to localhost:9292, how can i modify it? Thank you so much.

**Comment by sergekatzmann** [comment]
It seems that docker updates changed the way the network binding is handled. I saw a lot of different problems in this area in the last time.

Try to start the container with:
`
docker run --rm=true --net=host -p 9292:9292 sergekatzmann/openvas8-complete /opt/arachni/bin/arachni_web
`
