### ISSUE TITLE
in fact, i run docker build and docker run many many times, but the openvas container never run successfully.

### ISSUE THREAD

**Issue by tuhaolam** [sergekatzmann/openvas8-complete#2]
There are severval problem i face during installing as follow:
1."gsad main:WARNING:2016-11-11 14h41.14 utc:447: MHD: Call to socket failed: Address family not supported by protocol"
2."lib  serv:WARNING:2016-11-11 15h06.24 utc:948: Failed to shake hands with peer: The signature algorithm is not supported.
md   main:   INFO:2016-11-11 15h40.09 utc:1058:    OpenVAS Manager version 6.0.6 (DB revision 146)
md   main:   INFO:2016-11-11 15h40.09 utc:1058: rebuild_nvt_cache_retry: Reloading NVT cache
md   main:   INFO:2016-11-11 15h40.09 utc:1059: update_or_rebuild_nvt_cache: Rebuilding NVT cache
md   main:   INFO:2016-11-11 15h40.10 utc:1059:    Updating NVT cache.
lib  serv:WARNING:2016-11-13 13h59.09 utc:2639: Failed to shutdown server socket
md   main:CRITICAL:2016-11-13 13h59.09 utc:2639: serve_client: failed to attach client session to socket 10
lib  serv:WARNING:2016-11-13 13h59.09 utc:2639:    Failed to gnutls_bye: GnuTLS internal error."

**Comment by sergekatzmann** [comment]
Same for me. There seems to be a gnutls problem at this point. I guess the combination of debian 7.8 with now updated packages (in comparison to the state when I've developed this) and the used version of the openvas is not working properly together. I tried to switch to newer versions of openvas 8 but debian 7.8 do not have gnutls >=3.2 out of the  box. 
Unfortunately I don't have much spare time to address and solve this problem in the near future.

**Comment by tuhaolam** [comment]
I'm sure that my installment is ok, as the run result shows:'It seems like your OpenVAS-8 installation is OK.'
But, too many times, the openvasmd log shows:'lib  serv:WARNING:2016-11-15 15h04.38 utc:3757: Failed to shake hands with peer: A TLS packet with unexpected length was received.
lib  serv:WARNING:2016-11-15 15h04.38 utc:3757: Failed to shutdown server socket
md   main:CRITICAL:2016-11-15 15h04.38 utc:3757: serve_client: failed to attach client session to socket 10
lib  serv:WARNING:2016-11-15 15h04.38 utc:3757:    Failed to gnutls_bye: GnuTLS internal error.'

I feel so dispointed, it takes me severval weeks, but never get better.

**Comment by sergekatzmann** [comment]
Sorry to hear that.
You can try the Docker Container from @mikesplain
`
https://github.com/mikesplain/openvas-docker
`
or
`
https://github.com/mikesplain/openvas-docker/tree/9-beta
`

Perhaps you can get this to work or find the missing link using Mikes solution. 

It is as well possible to try and use the official OpenVAS 8 VM.
`
http://www.openvas.org/vm.html
`
